#!/usr/bin/env python3

import os
import sys
import signal
import locale
import gettext

VERSION = '0.5.1'
signal.signal(signal.SIGINT, signal.SIG_DFL)

locale.bindtextdomain("openswitcher", os.path.join(pkgdir, 'po'))
gettext.install("openswitcher", os.path.join(pkgdir, 'po'))

if __name__ == '__main__':
    import gi
    from gi.repository import Gio

    pkgdir = os.path.dirname(sys.executable)
    resource = Gio.Resource.load(os.path.join(pkgdir, 'atem.gresource'))

    resource._register()

    from gtk_switcher import __main__
    sys.exit(__main__.main(VERSION))
