#!/usr/bin/env python3

import os
import sys
import signal
import gettext
import ctypes

VERSION = '0.5.1'
signal.signal(signal.SIGINT, signal.SIG_DFL)

pkgdir = os.path.dirname(sys.executable)
localedir = os.path.join(pkgdir, 'share/locale')

import ctypes
libintl = ctypes.cdll.LoadLibrary("libintl-8.dll")
libintl.bindtextdomain("openswitcher".encode(), localedir.encode(sys.getfilesystemencoding()))
libintl.bind_textdomain_codeset("openswitcher".encode(), 'UTF-8'.encode())
gettext.install("openswitcher", localedir)
gettext.textdomain("openswitcher")

if __name__ == '__main__':
    import gi
    from gi.repository import Gio

    resource = Gio.Resource.load(os.path.join(pkgdir, 'atem.gresource'))

    resource._register()

    from gtk_switcher import __main__
    sys.exit(__main__.main(VERSION))
