# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  windows:
    runs-on: windows-2019
    strategy:
      matrix:
        include: [
          { msystem: MINGW64, arch: x86_64 },
          { msystem: MINGW32, arch: i686 },
        ]
    defaults:
      run:
        shell: msys2 {0}
    env:
      ARCH: ${{ matrix.arch }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: "https://git.sr.ht/~martijnbraam/pyatem"
          fetch-depth: 0

      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true

      - name: Install build dependencies
        run: |
          pacman --noconfirm -S --needed mingw-w64-$ARCH-python mingw-w64-$ARCH-gettext mingw-w64-$ARCH-gspell mingw-w64-$ARCH-gtk3 mingw-w64-$ARCH-python-chardet mingw-w64-$ARCH-python-pip mingw-w64-$ARCH-python-gobject mingw-w64-$ARCH-libusb mingw-w64-$ARCH-gcc mingw-w64-$ARCH-libhandy mingw-w64-$ARCH-python-cx-freeze mingw-w64-$ARCH-pywin32
      - name: Build installer
        run: |
          python3 windows/setup.py bdist_msi
          mv build/exe.* build/openswitcher
      - name: Archive installer artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows-${{ matrix.arch }}-installer
          path: dist

      - name: Archive package artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows-${{ matrix.arch }}-package
          path: build
